version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "UTC"
    reviewers:
      - "stormingluke"
    target-branch: "main"
    labels: ["dependencies"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "UTC"
    reviewers:
      - "stormingluke"
    target-branch: "main"
    labels: [ "dependencies" ]